[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "vite --host 0.0.0.0"
  targetPort = 5173

[functions]
  directory = "apps/server/netlify"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/telemetry*"
  to = "/.netlify/functions/telemetry/:splat"
  status = 200
